# tasks file for ansible-geoip
---
- stat: "path={{ geo_ip_folder }}/GeoLite2-City.mmdb"
  register: geo_st

- when: (geo_ip_override | default(false)) or (geo_st.stat.exists is defined and not geo_st.stat.exists)
  block:
   - name: Download GeoLite City database
     get_url: "url={{ geo_ip_url }} dest=/tmp"
     register: download_geolite
     tags:
         - geoip

   - name: Ensure that GeoIP folder exists
     file: "path={{ geo_ip_folder }} state=directory mode=0755"
     tags:
         - geoip

   - name: Unpack GeoLite database
     shell: "gunzip {{download_geolite.dest}} && mv /tmp/GeoLite2-City.mmdb {{ geo_ip_folder }}/"
     tags:
         - geoip
